name: "Close stale issues and pull requests"

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-stale:
    runs-on: ubuntu-latest
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30
          days-before-issue-close: 0
          days-before-pr-stale: 30
          days-before-pr-close: 0
          stale-issue-message: "This issue has not had any updates for 30 days and will be closed."
          stale-pr-message: "This pull request has not had any updates for 30 days and will be closed."
          delete-branch: true
