name: Sync common files (Organization)

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sync files
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT_ORGANIZATION }}
          CONFIG_PATH: .github/sync-organization.yml
          BRANCH_PREFIX: file-sync
          COMMIT_PREFIX: "chore:"
          PR_LABELS: chore
          ASSIGNEES: HU-Lee
